{% set name = "emsarray" %}
{% set version = "0.4.0" %}
{% set build_num = 0 %}

package:
  name: {{ name|lower }}-meta
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/emsarray-{{ version }}.tar.gz
  sha256: bb8d00a103934b325fb3b18ac126998f932c4412dcd4fe6c2df0fb1cad2095fa

build:
  number: {{ build_num }}

outputs:
  - name: emsarray-core
    build:
      noarch: python
      entry_points:
        - emsarray = emsarray.cli:main
    script: build_base.sh

    requirements:
      host:
        - python >=3.8
        - pip
      run:
        - python >=3.8
        - bottleneck >=1.3
        - dask >=2022.1.0
        - geojson >=2.5.0
        - importlib_metadata >=4.0.0
        - netcdf4 >=1.5.3
        - numpy >=1.18.0
        - packaging >=21.3
        - pyshp >=2.3.0
        - shapely >=2.0.0
        - xarray >=0.18.2
    test:
      imports:
        - emsarray
      commands:
        - pip check
        - emsarray --help
      requires:
        - pip

  - name: emsarray
    build:
      noarch: generic
      string: {{ build_num }}_fullpackage
    requirements:
      run:
        - {{ pin_subpackage("emsarray-core", exact=True) }}
          # plot extra
        - cartopy >=0.20.0
        - matplotlib-base >=3.4.3
        - pykdtree >=1.2.2
          # tutorial extra
        - pooch >=1.3.0
    test:
      imports:
        - emsarray


about:
  home: https://pypi.org/project/emsarray/
  summary: Utilities for working with non-CF grid datasets
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENCE
  doc_url: https://emsarray.readthedocs.io/
  dev_url: https://github.com/csiro-coasts/emsarray/

extra:
  recipe-maintainers:
    - mx-moth
  feedstock-name: {{ name|lower }}
