{% set name = "emsarray" %}
{% set version = "0.9.0" %}
{% set build_num = 0 %}

package:
  name: {{ name|lower }}-meta
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/emsarray-{{ version }}.tar.gz
  sha256: d99029fe8380e18ef2791a379518aa903bed1b9e482fe5bafa8254d719c10723

build:
  number: {{ build_num }}

outputs:
  - name: emsarray-core
    build:
      noarch: python
      entry_points:
        - emsarray = emsarray.cli:main
    script: build_base.sh

    requirements:
      host:
        - python >=3.10
        - pip
        - setuptools
      run:
        - python >=3.10
        - bottleneck >=1.3
        - dask >=2023.07.0
        - geojson >=3.0
        - netcdf4 >=1.6.4
        - numpy >=1.24
        - packaging >=23.1
        - pyshp >=2.3.0
        - shapely >=2.0.0
        - xarray >=2023.5
    test:
      imports:
        - emsarray
      commands:
        - pip check
        - emsarray --help
      requires:
        - pip

  - name: emsarray
    build:
      noarch: generic
      string: {{ build_num }}_fullpackage
    requirements:
      run:
        - {{ pin_subpackage("emsarray-core", exact=True) }}
          # plot extra
        - cartopy >=0.21.1
        - cfunits >=3.3.5
        - matplotlib-base >=3.7
        - pykdtree >=1.3.5
          # tutorial extra
        - pooch >=1.7
    test:
      imports:
        - emsarray


about:
  home: https://pypi.org/project/emsarray/
  summary: Utilities for working with non-CF grid datasets
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://emsarray.readthedocs.io/
  dev_url: https://github.com/csiro-coasts/emsarray/

extra:
  recipe-maintainers:
    - david-sh-csiro
    - mx-moth
  feedstock-name: {{ name|lower }}
